import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { routing } from "@/i18n/routing";

import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import MobileMenu from "@/components/MobileMenu";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="max-w-[1600px] mx-auto">
          <Header />
          <NextIntlClientProvider>
            <section>{children}</section>
          </NextIntlClientProvider>
        </section>
        <div className="flex md:hidden mt-[100px]">
          <MobileMenu />
        </div>
   
      </body>
    </html>
  );
}
